# Generated by Django 4.2.13 on 2024-07-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0010_place_cinema_place_hall_alter_place_row'),
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AddField(
            model_name='order',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.hall', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='order',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.row', verbose_name='Ряд'),
        ),
    ]
