# Generated by Django 4.2.13 on 2024-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cinema_order_hall_order_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked',
            field=models.BooleanField(default=True, verbose_name='Забронирован'),
        ),
    ]
