# Generated by Django 4.2.13 on 2024-07-10 14:09

from django.db import migrations, models
import utils.image_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=128, verbose_name='Страна')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('starring', models.TextField(verbose_name='В главных ролях')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=utils.image_upload.upload_instance_image, verbose_name='Постер')),
            ],
        ),
    ]
