# Generated by Django 4.2.13 on 2024-07-10 14:27

from django.db import migrations, models
import utils.image_upload


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=utils.image_upload.upload_instance_image, verbose_name='Фото')),
                ('address', models.CharField(verbose_name='Адрес')),
            ],
        ),
    ]
