# Generated by Django 4.2.13 on 2024-07-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Место')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row', to='cinemas.row', verbose_name='Ряд')),
            ],
        ),
    ]
