# Generated by Django 4.2.13 on 2024-07-18 14:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hall',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cinema', chained_model_field='cinema', default=None, on_delete=django.db.models.deletion.CASCADE, to='cinemas.hall'),
        ),
    ]
