# Generated by Django 4.2.13 on 2024-07-22 13:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_movie_genre_alter_session_hall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинотеатр', 'verbose_name_plural': 'Кинотеатры'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'verbose_name': 'Ряд', 'verbose_name_plural': 'Ряды'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AddField(
            model_name='row',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='row',
            name='hall',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cinema', chained_model_field='cinema', default=None, on_delete=django.db.models.deletion.CASCADE, to='cinemas.hall', verbose_name='Зал'),
        ),
    ]
