# Generated by Django 4.2.13 on 2024-07-22 13:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_alter_cinema_options_alter_hall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AddField(
            model_name='place',
            name='hall',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cinema', chained_model_field='cinema', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='place',
            name='row',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hall', chained_model_field='hall', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.row', verbose_name='Ряд'),
        ),
    ]
